# Generated by Django 3.1.6 on 2021-02-27 05:32

import random
from django.db import migrations
from en2bn.hashing import *

"""
    This migrations file is for populating ABValue Table
"""
def seedData(apps, schema_editor):
    ab_value = apps.get_model('en2bn', 'abvalue')
    for i in range(0, M):
        a = random.randint(1, PRIME)
        b = random.randint(0, PRIME)
        ab_value.objects.create(p_hash_indx=i, a=a, b=b)


class Migration(migrations.Migration):
    dependencies = [
        ('en2bn', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seedData)
    ]