# Generated by Django 3.1.6 on 2021-02-23 12:55

import json
import random
import urllib.request
from django.db import migrations
from en2bn.hashing import *

"""
This migration file is to populate Word List and assign temporary primary hash and secondary hash 
"""

def seedData(apps, schema_editor):
    url = 'https://raw.githubusercontent.com/MinhasKamal/BengaliDictionary/master/BengaliDictionary.json'
    response = urllib.request.urlopen(url)
    ab_value = apps.get_model('en2bn', 'abvalue')
    word_list = apps.get_model('en2bn', 'wordlist')
    data = json.loads(response.read())
    for word in data:
        key = string2number(str(word['en']).strip().casefold())
        p_hash = calculateFirstHash(key)
        ab = ab_value.objects.get(p_hash_indx=p_hash)
        m = ab.m
        new_b = ab.b
        new_a = ab.a
        s_hash = calculateSecondHash(key, new_a, new_b, m)

        if 'sents' in word and 'en_syns' in word and 'bn_syns' in word:
            w = word_list.objects.create(p_hash_indx=p_hash, s_hash_indx=s_hash, bn=word['bn'], en=word['en'],
                                         bn_syns=word['bn_syns'], en_syns=word['en_syns'], sents=word['sents'])
        # print(w)
        else:
            w = word_list.objects.create(p_hash_indx=p_hash, s_hash_indx=s_hash, bn=word['bn'], en=word['en'])




class Migration(migrations.Migration):

    dependencies = [
        ('en2bn', '0002_auto_20210223_1254'),
    ]

    operations = [
        migrations.RunPython(seedData),
    ]
